//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9168
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.9168.
// 
#pragma warning disable 1591

namespace DJEngine.WSMotorDDJJ {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_MOTOR_DDJJSoap", Namespace="http://tempuri.org/")]
    public partial class WS_MOTOR_DDJJ : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Insert_HeaderOperationCompleted;
        
        private System.Threading.SendOrPostCallback Proc_DdjjOperationCompleted;
        
        private System.Threading.SendOrPostCallback Proc_Ddjj_IdOperationCompleted;
        
        private System.Threading.SendOrPostCallback Proc_LibroOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstTiposSocietariosFiltradosOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstWorkFlowOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLegalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstTiposSocietariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstTiposDocumentosOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstCategoriaPEPOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstSubCategoriasPEPOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstVinculoPEPOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstTiposClaveFiscalOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstTiposCargoOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstTiposCargoFiltradosOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstTiposDJOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstTiposMonedasOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstTiposValuacionFiltradosOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstTiposValuacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstTiposInstrumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstTiposCuentaBancoOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstTiposDictamenOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstTiposAsambleaOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstTiposDocRubricaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMembreteOperationCompleted;
        
        private System.Threading.SendOrPostCallback LstTiposEstadosCivilesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_MOTOR_DDJJ() {
            this.Url = global::DJEngine.Properties.Settings.Default.DJEngine_WSMotorDDJJ_WS_MOTOR_DDJJ;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Insert_HeaderCompletedEventHandler Insert_HeaderCompleted;
        
        /// <remarks/>
        public event Proc_DdjjCompletedEventHandler Proc_DdjjCompleted;
        
        /// <remarks/>
        public event Proc_Ddjj_IdCompletedEventHandler Proc_Ddjj_IdCompleted;
        
        /// <remarks/>
        public event Proc_LibroCompletedEventHandler Proc_LibroCompleted;
        
        /// <remarks/>
        public event LstTiposSocietariosFiltradosCompletedEventHandler LstTiposSocietariosFiltradosCompleted;
        
        /// <remarks/>
        public event LstWorkFlowCompletedEventHandler LstWorkFlowCompleted;
        
        /// <remarks/>
        public event GetLegalesCompletedEventHandler GetLegalesCompleted;
        
        /// <remarks/>
        public event LstTiposSocietariosCompletedEventHandler LstTiposSocietariosCompleted;
        
        /// <remarks/>
        public event LstTiposDocumentosCompletedEventHandler LstTiposDocumentosCompleted;
        
        /// <remarks/>
        public event LstCategoriaPEPCompletedEventHandler LstCategoriaPEPCompleted;
        
        /// <remarks/>
        public event LstSubCategoriasPEPCompletedEventHandler LstSubCategoriasPEPCompleted;
        
        /// <remarks/>
        public event LstVinculoPEPCompletedEventHandler LstVinculoPEPCompleted;
        
        /// <remarks/>
        public event LstTiposClaveFiscalCompletedEventHandler LstTiposClaveFiscalCompleted;
        
        /// <remarks/>
        public event LstTiposCargoCompletedEventHandler LstTiposCargoCompleted;
        
        /// <remarks/>
        public event LstTiposCargoFiltradosCompletedEventHandler LstTiposCargoFiltradosCompleted;
        
        /// <remarks/>
        public event LstTiposDJCompletedEventHandler LstTiposDJCompleted;
        
        /// <remarks/>
        public event LstTiposMonedasCompletedEventHandler LstTiposMonedasCompleted;
        
        /// <remarks/>
        public event LstTiposValuacionFiltradosCompletedEventHandler LstTiposValuacionFiltradosCompleted;
        
        /// <remarks/>
        public event LstTiposValuacionCompletedEventHandler LstTiposValuacionCompleted;
        
        /// <remarks/>
        public event LstTiposInstrumentoCompletedEventHandler LstTiposInstrumentoCompleted;
        
        /// <remarks/>
        public event LstTiposCuentaBancoCompletedEventHandler LstTiposCuentaBancoCompleted;
        
        /// <remarks/>
        public event LstTiposDictamenCompletedEventHandler LstTiposDictamenCompleted;
        
        /// <remarks/>
        public event LstTiposAsambleaCompletedEventHandler LstTiposAsambleaCompleted;
        
        /// <remarks/>
        public event LstTiposDocRubricaCompletedEventHandler LstTiposDocRubricaCompleted;
        
        /// <remarks/>
        public event GetMembreteCompletedEventHandler GetMembreteCompleted;
        
        /// <remarks/>
        public event LstTiposEstadosCivilesCompletedEventHandler LstTiposEstadosCivilesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_Header", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("DDJJ_ID")]
        public long Insert_Header(DDJJHeader header, out int Status, out string Mensaje) {
            object[] results = this.Invoke("Insert_Header", new object[] {
                        header});
            Status = ((int)(results[1]));
            Mensaje = ((string)(results[2]));
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void Insert_HeaderAsync(DDJJHeader header) {
            this.Insert_HeaderAsync(header, null);
        }
        
        /// <remarks/>
        public void Insert_HeaderAsync(DDJJHeader header, object userState) {
            if ((this.Insert_HeaderOperationCompleted == null)) {
                this.Insert_HeaderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_HeaderOperationCompleted);
            }
            this.InvokeAsync("Insert_Header", new object[] {
                        header}, this.Insert_HeaderOperationCompleted, userState);
        }
        
        private void OnInsert_HeaderOperationCompleted(object arg) {
            if ((this.Insert_HeaderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Insert_HeaderCompleted(this, new Insert_HeaderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Proc_Ddjj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Status")]
        public int Proc_Ddjj(long DDJJ_ID, out string Mensaje) {
            object[] results = this.Invoke("Proc_Ddjj", new object[] {
                        DDJJ_ID});
            Mensaje = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Proc_DdjjAsync(long DDJJ_ID) {
            this.Proc_DdjjAsync(DDJJ_ID, null);
        }
        
        /// <remarks/>
        public void Proc_DdjjAsync(long DDJJ_ID, object userState) {
            if ((this.Proc_DdjjOperationCompleted == null)) {
                this.Proc_DdjjOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProc_DdjjOperationCompleted);
            }
            this.InvokeAsync("Proc_Ddjj", new object[] {
                        DDJJ_ID}, this.Proc_DdjjOperationCompleted, userState);
        }
        
        private void OnProc_DdjjOperationCompleted(object arg) {
            if ((this.Proc_DdjjCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Proc_DdjjCompleted(this, new Proc_DdjjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Proc_Ddjj_Id", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Status")]
        public int Proc_Ddjj_Id(long DDJJ_ID, out string Mensaje, out int DJ_ID) {
            object[] results = this.Invoke("Proc_Ddjj_Id", new object[] {
                        DDJJ_ID});
            Mensaje = ((string)(results[1]));
            DJ_ID = ((int)(results[2]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Proc_Ddjj_IdAsync(long DDJJ_ID) {
            this.Proc_Ddjj_IdAsync(DDJJ_ID, null);
        }
        
        /// <remarks/>
        public void Proc_Ddjj_IdAsync(long DDJJ_ID, object userState) {
            if ((this.Proc_Ddjj_IdOperationCompleted == null)) {
                this.Proc_Ddjj_IdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProc_Ddjj_IdOperationCompleted);
            }
            this.InvokeAsync("Proc_Ddjj_Id", new object[] {
                        DDJJ_ID}, this.Proc_Ddjj_IdOperationCompleted, userState);
        }
        
        private void OnProc_Ddjj_IdOperationCompleted(object arg) {
            if ((this.Proc_Ddjj_IdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Proc_Ddjj_IdCompleted(this, new Proc_Ddjj_IdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Proc_Libro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Status")]
        public int Proc_Libro(long DDJJ_ID, long DOCID, string DOC, string DEN, string NRU, string FRU, string FOL, string HAS, out string Mensaje) {
            object[] results = this.Invoke("Proc_Libro", new object[] {
                        DDJJ_ID,
                        DOCID,
                        DOC,
                        DEN,
                        NRU,
                        FRU,
                        FOL,
                        HAS});
            Mensaje = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Proc_LibroAsync(long DDJJ_ID, long DOCID, string DOC, string DEN, string NRU, string FRU, string FOL, string HAS) {
            this.Proc_LibroAsync(DDJJ_ID, DOCID, DOC, DEN, NRU, FRU, FOL, HAS, null);
        }
        
        /// <remarks/>
        public void Proc_LibroAsync(long DDJJ_ID, long DOCID, string DOC, string DEN, string NRU, string FRU, string FOL, string HAS, object userState) {
            if ((this.Proc_LibroOperationCompleted == null)) {
                this.Proc_LibroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProc_LibroOperationCompleted);
            }
            this.InvokeAsync("Proc_Libro", new object[] {
                        DDJJ_ID,
                        DOCID,
                        DOC,
                        DEN,
                        NRU,
                        FRU,
                        FOL,
                        HAS}, this.Proc_LibroOperationCompleted, userState);
        }
        
        private void OnProc_LibroOperationCompleted(object arg) {
            if ((this.Proc_LibroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Proc_LibroCompleted(this, new Proc_LibroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstTiposSocietariosFiltrados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstTiposSocietariosFiltrados(int TipoDDJJ) {
            object[] results = this.Invoke("LstTiposSocietariosFiltrados", new object[] {
                        TipoDDJJ});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstTiposSocietariosFiltradosAsync(int TipoDDJJ) {
            this.LstTiposSocietariosFiltradosAsync(TipoDDJJ, null);
        }
        
        /// <remarks/>
        public void LstTiposSocietariosFiltradosAsync(int TipoDDJJ, object userState) {
            if ((this.LstTiposSocietariosFiltradosOperationCompleted == null)) {
                this.LstTiposSocietariosFiltradosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstTiposSocietariosFiltradosOperationCompleted);
            }
            this.InvokeAsync("LstTiposSocietariosFiltrados", new object[] {
                        TipoDDJJ}, this.LstTiposSocietariosFiltradosOperationCompleted, userState);
        }
        
        private void OnLstTiposSocietariosFiltradosOperationCompleted(object arg) {
            if ((this.LstTiposSocietariosFiltradosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstTiposSocietariosFiltradosCompleted(this, new LstTiposSocietariosFiltradosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstWorkFlow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstWorkFlow(int TipoDDJJ) {
            object[] results = this.Invoke("LstWorkFlow", new object[] {
                        TipoDDJJ});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstWorkFlowAsync(int TipoDDJJ) {
            this.LstWorkFlowAsync(TipoDDJJ, null);
        }
        
        /// <remarks/>
        public void LstWorkFlowAsync(int TipoDDJJ, object userState) {
            if ((this.LstWorkFlowOperationCompleted == null)) {
                this.LstWorkFlowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstWorkFlowOperationCompleted);
            }
            this.InvokeAsync("LstWorkFlow", new object[] {
                        TipoDDJJ}, this.LstWorkFlowOperationCompleted, userState);
        }
        
        private void OnLstWorkFlowOperationCompleted(object arg) {
            if ((this.LstWorkFlowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstWorkFlowCompleted(this, new LstWorkFlowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLegales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetLegales(int TipoDDJJ) {
            object[] results = this.Invoke("GetLegales", new object[] {
                        TipoDDJJ});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetLegalesAsync(int TipoDDJJ) {
            this.GetLegalesAsync(TipoDDJJ, null);
        }
        
        /// <remarks/>
        public void GetLegalesAsync(int TipoDDJJ, object userState) {
            if ((this.GetLegalesOperationCompleted == null)) {
                this.GetLegalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLegalesOperationCompleted);
            }
            this.InvokeAsync("GetLegales", new object[] {
                        TipoDDJJ}, this.GetLegalesOperationCompleted, userState);
        }
        
        private void OnGetLegalesOperationCompleted(object arg) {
            if ((this.GetLegalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLegalesCompleted(this, new GetLegalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstTiposSocietarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstTiposSocietarios() {
            object[] results = this.Invoke("LstTiposSocietarios", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstTiposSocietariosAsync() {
            this.LstTiposSocietariosAsync(null);
        }
        
        /// <remarks/>
        public void LstTiposSocietariosAsync(object userState) {
            if ((this.LstTiposSocietariosOperationCompleted == null)) {
                this.LstTiposSocietariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstTiposSocietariosOperationCompleted);
            }
            this.InvokeAsync("LstTiposSocietarios", new object[0], this.LstTiposSocietariosOperationCompleted, userState);
        }
        
        private void OnLstTiposSocietariosOperationCompleted(object arg) {
            if ((this.LstTiposSocietariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstTiposSocietariosCompleted(this, new LstTiposSocietariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstTiposDocumentos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstTiposDocumentos() {
            object[] results = this.Invoke("LstTiposDocumentos", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstTiposDocumentosAsync() {
            this.LstTiposDocumentosAsync(null);
        }
        
        /// <remarks/>
        public void LstTiposDocumentosAsync(object userState) {
            if ((this.LstTiposDocumentosOperationCompleted == null)) {
                this.LstTiposDocumentosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstTiposDocumentosOperationCompleted);
            }
            this.InvokeAsync("LstTiposDocumentos", new object[0], this.LstTiposDocumentosOperationCompleted, userState);
        }
        
        private void OnLstTiposDocumentosOperationCompleted(object arg) {
            if ((this.LstTiposDocumentosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstTiposDocumentosCompleted(this, new LstTiposDocumentosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstCategoriaPEP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstCategoriaPEP() {
            object[] results = this.Invoke("LstCategoriaPEP", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstCategoriaPEPAsync() {
            this.LstCategoriaPEPAsync(null);
        }
        
        /// <remarks/>
        public void LstCategoriaPEPAsync(object userState) {
            if ((this.LstCategoriaPEPOperationCompleted == null)) {
                this.LstCategoriaPEPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstCategoriaPEPOperationCompleted);
            }
            this.InvokeAsync("LstCategoriaPEP", new object[0], this.LstCategoriaPEPOperationCompleted, userState);
        }
        
        private void OnLstCategoriaPEPOperationCompleted(object arg) {
            if ((this.LstCategoriaPEPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstCategoriaPEPCompleted(this, new LstCategoriaPEPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstSubCategoriasPEP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstSubCategoriasPEP(int Codigo) {
            object[] results = this.Invoke("LstSubCategoriasPEP", new object[] {
                        Codigo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstSubCategoriasPEPAsync(int Codigo) {
            this.LstSubCategoriasPEPAsync(Codigo, null);
        }
        
        /// <remarks/>
        public void LstSubCategoriasPEPAsync(int Codigo, object userState) {
            if ((this.LstSubCategoriasPEPOperationCompleted == null)) {
                this.LstSubCategoriasPEPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstSubCategoriasPEPOperationCompleted);
            }
            this.InvokeAsync("LstSubCategoriasPEP", new object[] {
                        Codigo}, this.LstSubCategoriasPEPOperationCompleted, userState);
        }
        
        private void OnLstSubCategoriasPEPOperationCompleted(object arg) {
            if ((this.LstSubCategoriasPEPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstSubCategoriasPEPCompleted(this, new LstSubCategoriasPEPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstVinculoPEP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstVinculoPEP() {
            object[] results = this.Invoke("LstVinculoPEP", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstVinculoPEPAsync() {
            this.LstVinculoPEPAsync(null);
        }
        
        /// <remarks/>
        public void LstVinculoPEPAsync(object userState) {
            if ((this.LstVinculoPEPOperationCompleted == null)) {
                this.LstVinculoPEPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstVinculoPEPOperationCompleted);
            }
            this.InvokeAsync("LstVinculoPEP", new object[0], this.LstVinculoPEPOperationCompleted, userState);
        }
        
        private void OnLstVinculoPEPOperationCompleted(object arg) {
            if ((this.LstVinculoPEPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstVinculoPEPCompleted(this, new LstVinculoPEPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstTiposClaveFiscal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstTiposClaveFiscal() {
            object[] results = this.Invoke("LstTiposClaveFiscal", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstTiposClaveFiscalAsync() {
            this.LstTiposClaveFiscalAsync(null);
        }
        
        /// <remarks/>
        public void LstTiposClaveFiscalAsync(object userState) {
            if ((this.LstTiposClaveFiscalOperationCompleted == null)) {
                this.LstTiposClaveFiscalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstTiposClaveFiscalOperationCompleted);
            }
            this.InvokeAsync("LstTiposClaveFiscal", new object[0], this.LstTiposClaveFiscalOperationCompleted, userState);
        }
        
        private void OnLstTiposClaveFiscalOperationCompleted(object arg) {
            if ((this.LstTiposClaveFiscalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstTiposClaveFiscalCompleted(this, new LstTiposClaveFiscalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstTiposCargo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstTiposCargo() {
            object[] results = this.Invoke("LstTiposCargo", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstTiposCargoAsync() {
            this.LstTiposCargoAsync(null);
        }
        
        /// <remarks/>
        public void LstTiposCargoAsync(object userState) {
            if ((this.LstTiposCargoOperationCompleted == null)) {
                this.LstTiposCargoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstTiposCargoOperationCompleted);
            }
            this.InvokeAsync("LstTiposCargo", new object[0], this.LstTiposCargoOperationCompleted, userState);
        }
        
        private void OnLstTiposCargoOperationCompleted(object arg) {
            if ((this.LstTiposCargoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstTiposCargoCompleted(this, new LstTiposCargoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstTiposCargoFiltrados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstTiposCargoFiltrados(int TipoSocId) {
            object[] results = this.Invoke("LstTiposCargoFiltrados", new object[] {
                        TipoSocId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstTiposCargoFiltradosAsync(int TipoSocId) {
            this.LstTiposCargoFiltradosAsync(TipoSocId, null);
        }
        
        /// <remarks/>
        public void LstTiposCargoFiltradosAsync(int TipoSocId, object userState) {
            if ((this.LstTiposCargoFiltradosOperationCompleted == null)) {
                this.LstTiposCargoFiltradosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstTiposCargoFiltradosOperationCompleted);
            }
            this.InvokeAsync("LstTiposCargoFiltrados", new object[] {
                        TipoSocId}, this.LstTiposCargoFiltradosOperationCompleted, userState);
        }
        
        private void OnLstTiposCargoFiltradosOperationCompleted(object arg) {
            if ((this.LstTiposCargoFiltradosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstTiposCargoFiltradosCompleted(this, new LstTiposCargoFiltradosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstTiposDJ", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstTiposDJ() {
            object[] results = this.Invoke("LstTiposDJ", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstTiposDJAsync() {
            this.LstTiposDJAsync(null);
        }
        
        /// <remarks/>
        public void LstTiposDJAsync(object userState) {
            if ((this.LstTiposDJOperationCompleted == null)) {
                this.LstTiposDJOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstTiposDJOperationCompleted);
            }
            this.InvokeAsync("LstTiposDJ", new object[0], this.LstTiposDJOperationCompleted, userState);
        }
        
        private void OnLstTiposDJOperationCompleted(object arg) {
            if ((this.LstTiposDJCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstTiposDJCompleted(this, new LstTiposDJCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstTiposMonedas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstTiposMonedas() {
            object[] results = this.Invoke("LstTiposMonedas", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstTiposMonedasAsync() {
            this.LstTiposMonedasAsync(null);
        }
        
        /// <remarks/>
        public void LstTiposMonedasAsync(object userState) {
            if ((this.LstTiposMonedasOperationCompleted == null)) {
                this.LstTiposMonedasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstTiposMonedasOperationCompleted);
            }
            this.InvokeAsync("LstTiposMonedas", new object[0], this.LstTiposMonedasOperationCompleted, userState);
        }
        
        private void OnLstTiposMonedasOperationCompleted(object arg) {
            if ((this.LstTiposMonedasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstTiposMonedasCompleted(this, new LstTiposMonedasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstTiposValuacionFiltrados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstTiposValuacionFiltrados(int TipoBienId) {
            object[] results = this.Invoke("LstTiposValuacionFiltrados", new object[] {
                        TipoBienId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstTiposValuacionFiltradosAsync(int TipoBienId) {
            this.LstTiposValuacionFiltradosAsync(TipoBienId, null);
        }
        
        /// <remarks/>
        public void LstTiposValuacionFiltradosAsync(int TipoBienId, object userState) {
            if ((this.LstTiposValuacionFiltradosOperationCompleted == null)) {
                this.LstTiposValuacionFiltradosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstTiposValuacionFiltradosOperationCompleted);
            }
            this.InvokeAsync("LstTiposValuacionFiltrados", new object[] {
                        TipoBienId}, this.LstTiposValuacionFiltradosOperationCompleted, userState);
        }
        
        private void OnLstTiposValuacionFiltradosOperationCompleted(object arg) {
            if ((this.LstTiposValuacionFiltradosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstTiposValuacionFiltradosCompleted(this, new LstTiposValuacionFiltradosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstTiposValuacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstTiposValuacion() {
            object[] results = this.Invoke("LstTiposValuacion", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstTiposValuacionAsync() {
            this.LstTiposValuacionAsync(null);
        }
        
        /// <remarks/>
        public void LstTiposValuacionAsync(object userState) {
            if ((this.LstTiposValuacionOperationCompleted == null)) {
                this.LstTiposValuacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstTiposValuacionOperationCompleted);
            }
            this.InvokeAsync("LstTiposValuacion", new object[0], this.LstTiposValuacionOperationCompleted, userState);
        }
        
        private void OnLstTiposValuacionOperationCompleted(object arg) {
            if ((this.LstTiposValuacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstTiposValuacionCompleted(this, new LstTiposValuacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstTiposInstrumento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstTiposInstrumento() {
            object[] results = this.Invoke("LstTiposInstrumento", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstTiposInstrumentoAsync() {
            this.LstTiposInstrumentoAsync(null);
        }
        
        /// <remarks/>
        public void LstTiposInstrumentoAsync(object userState) {
            if ((this.LstTiposInstrumentoOperationCompleted == null)) {
                this.LstTiposInstrumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstTiposInstrumentoOperationCompleted);
            }
            this.InvokeAsync("LstTiposInstrumento", new object[0], this.LstTiposInstrumentoOperationCompleted, userState);
        }
        
        private void OnLstTiposInstrumentoOperationCompleted(object arg) {
            if ((this.LstTiposInstrumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstTiposInstrumentoCompleted(this, new LstTiposInstrumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstTiposCuentaBanco", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstTiposCuentaBanco() {
            object[] results = this.Invoke("LstTiposCuentaBanco", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstTiposCuentaBancoAsync() {
            this.LstTiposCuentaBancoAsync(null);
        }
        
        /// <remarks/>
        public void LstTiposCuentaBancoAsync(object userState) {
            if ((this.LstTiposCuentaBancoOperationCompleted == null)) {
                this.LstTiposCuentaBancoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstTiposCuentaBancoOperationCompleted);
            }
            this.InvokeAsync("LstTiposCuentaBanco", new object[0], this.LstTiposCuentaBancoOperationCompleted, userState);
        }
        
        private void OnLstTiposCuentaBancoOperationCompleted(object arg) {
            if ((this.LstTiposCuentaBancoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstTiposCuentaBancoCompleted(this, new LstTiposCuentaBancoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstTiposDictamen", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstTiposDictamen() {
            object[] results = this.Invoke("LstTiposDictamen", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstTiposDictamenAsync() {
            this.LstTiposDictamenAsync(null);
        }
        
        /// <remarks/>
        public void LstTiposDictamenAsync(object userState) {
            if ((this.LstTiposDictamenOperationCompleted == null)) {
                this.LstTiposDictamenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstTiposDictamenOperationCompleted);
            }
            this.InvokeAsync("LstTiposDictamen", new object[0], this.LstTiposDictamenOperationCompleted, userState);
        }
        
        private void OnLstTiposDictamenOperationCompleted(object arg) {
            if ((this.LstTiposDictamenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstTiposDictamenCompleted(this, new LstTiposDictamenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstTiposAsamblea", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstTiposAsamblea() {
            object[] results = this.Invoke("LstTiposAsamblea", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstTiposAsambleaAsync() {
            this.LstTiposAsambleaAsync(null);
        }
        
        /// <remarks/>
        public void LstTiposAsambleaAsync(object userState) {
            if ((this.LstTiposAsambleaOperationCompleted == null)) {
                this.LstTiposAsambleaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstTiposAsambleaOperationCompleted);
            }
            this.InvokeAsync("LstTiposAsamblea", new object[0], this.LstTiposAsambleaOperationCompleted, userState);
        }
        
        private void OnLstTiposAsambleaOperationCompleted(object arg) {
            if ((this.LstTiposAsambleaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstTiposAsambleaCompleted(this, new LstTiposAsambleaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstTiposDocRubrica", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstTiposDocRubrica() {
            object[] results = this.Invoke("LstTiposDocRubrica", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstTiposDocRubricaAsync() {
            this.LstTiposDocRubricaAsync(null);
        }
        
        /// <remarks/>
        public void LstTiposDocRubricaAsync(object userState) {
            if ((this.LstTiposDocRubricaOperationCompleted == null)) {
                this.LstTiposDocRubricaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstTiposDocRubricaOperationCompleted);
            }
            this.InvokeAsync("LstTiposDocRubrica", new object[0], this.LstTiposDocRubricaOperationCompleted, userState);
        }
        
        private void OnLstTiposDocRubricaOperationCompleted(object arg) {
            if ((this.LstTiposDocRubricaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstTiposDocRubricaCompleted(this, new LstTiposDocRubricaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMembrete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetMembrete() {
            object[] results = this.Invoke("GetMembrete", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetMembreteAsync() {
            this.GetMembreteAsync(null);
        }
        
        /// <remarks/>
        public void GetMembreteAsync(object userState) {
            if ((this.GetMembreteOperationCompleted == null)) {
                this.GetMembreteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMembreteOperationCompleted);
            }
            this.InvokeAsync("GetMembrete", new object[0], this.GetMembreteOperationCompleted, userState);
        }
        
        private void OnGetMembreteOperationCompleted(object arg) {
            if ((this.GetMembreteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMembreteCompleted(this, new GetMembreteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LstTiposEstadosCiviles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LstTiposEstadosCiviles() {
            object[] results = this.Invoke("LstTiposEstadosCiviles", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LstTiposEstadosCivilesAsync() {
            this.LstTiposEstadosCivilesAsync(null);
        }
        
        /// <remarks/>
        public void LstTiposEstadosCivilesAsync(object userState) {
            if ((this.LstTiposEstadosCivilesOperationCompleted == null)) {
                this.LstTiposEstadosCivilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLstTiposEstadosCivilesOperationCompleted);
            }
            this.InvokeAsync("LstTiposEstadosCiviles", new object[0], this.LstTiposEstadosCivilesOperationCompleted, userState);
        }
        
        private void OnLstTiposEstadosCivilesOperationCompleted(object arg) {
            if ((this.LstTiposEstadosCivilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LstTiposEstadosCivilesCompleted(this, new LstTiposEstadosCivilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DDJJHeader {
        
        private string operacionField;
        
        private string codHashField;
        
        private string fechaField;
        
        private string tipoDDJJField;
        
        private string nroCorrField;
        
        private string campo01Field;
        
        private string campo02Field;
        
        private string campo03Field;
        
        private string campo04Field;
        
        private string campo05Field;
        
        private string campo06Field;
        
        private string campo07Field;
        
        private string campo08Field;
        
        private string campo09Field;
        
        private string campo10Field;
        
        private string campo11Field;
        
        private string campo12Field;
        
        private string campo13Field;
        
        private string campo14Field;
        
        private string campo15Field;
        
        private string campo16Field;
        
        private string campo17Field;
        
        private string campo18Field;
        
        private string campo19Field;
        
        private string campo20Field;
        
        private string campo21Field;
        
        private string campo22Field;
        
        private string campo23Field;
        
        private string campo24Field;
        
        private string campo25Field;
        
        private string campo26Field;
        
        private string campo27Field;
        
        private string campo28Field;
        
        private string campo29Field;
        
        private string campo30Field;
        
        private string campo31Field;
        
        private string campo32Field;
        
        private string campo33Field;
        
        private string campo34Field;
        
        private string campo35Field;
        
        private string campo36Field;
        
        private string campo37Field;
        
        private string campo38Field;
        
        private string campo39Field;
        
        private string campo40Field;
        
        private string campo41Field;
        
        private string campo42Field;
        
        private string campo43Field;
        
        private string campo44Field;
        
        private string campo45Field;
        
        private string campo46Field;
        
        private string campo47Field;
        
        private string campo48Field;
        
        private string campo49Field;
        
        private string campo50Field;
        
        /// <remarks/>
        public string Operacion {
            get {
                return this.operacionField;
            }
            set {
                this.operacionField = value;
            }
        }
        
        /// <remarks/>
        public string CodHash {
            get {
                return this.codHashField;
            }
            set {
                this.codHashField = value;
            }
        }
        
        /// <remarks/>
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public string TipoDDJJ {
            get {
                return this.tipoDDJJField;
            }
            set {
                this.tipoDDJJField = value;
            }
        }
        
        /// <remarks/>
        public string NroCorr {
            get {
                return this.nroCorrField;
            }
            set {
                this.nroCorrField = value;
            }
        }
        
        /// <remarks/>
        public string Campo01 {
            get {
                return this.campo01Field;
            }
            set {
                this.campo01Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo02 {
            get {
                return this.campo02Field;
            }
            set {
                this.campo02Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo03 {
            get {
                return this.campo03Field;
            }
            set {
                this.campo03Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo04 {
            get {
                return this.campo04Field;
            }
            set {
                this.campo04Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo05 {
            get {
                return this.campo05Field;
            }
            set {
                this.campo05Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo06 {
            get {
                return this.campo06Field;
            }
            set {
                this.campo06Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo07 {
            get {
                return this.campo07Field;
            }
            set {
                this.campo07Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo08 {
            get {
                return this.campo08Field;
            }
            set {
                this.campo08Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo09 {
            get {
                return this.campo09Field;
            }
            set {
                this.campo09Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo10 {
            get {
                return this.campo10Field;
            }
            set {
                this.campo10Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo11 {
            get {
                return this.campo11Field;
            }
            set {
                this.campo11Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo12 {
            get {
                return this.campo12Field;
            }
            set {
                this.campo12Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo13 {
            get {
                return this.campo13Field;
            }
            set {
                this.campo13Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo14 {
            get {
                return this.campo14Field;
            }
            set {
                this.campo14Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo15 {
            get {
                return this.campo15Field;
            }
            set {
                this.campo15Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo16 {
            get {
                return this.campo16Field;
            }
            set {
                this.campo16Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo17 {
            get {
                return this.campo17Field;
            }
            set {
                this.campo17Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo18 {
            get {
                return this.campo18Field;
            }
            set {
                this.campo18Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo19 {
            get {
                return this.campo19Field;
            }
            set {
                this.campo19Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo20 {
            get {
                return this.campo20Field;
            }
            set {
                this.campo20Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo21 {
            get {
                return this.campo21Field;
            }
            set {
                this.campo21Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo22 {
            get {
                return this.campo22Field;
            }
            set {
                this.campo22Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo23 {
            get {
                return this.campo23Field;
            }
            set {
                this.campo23Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo24 {
            get {
                return this.campo24Field;
            }
            set {
                this.campo24Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo25 {
            get {
                return this.campo25Field;
            }
            set {
                this.campo25Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo26 {
            get {
                return this.campo26Field;
            }
            set {
                this.campo26Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo27 {
            get {
                return this.campo27Field;
            }
            set {
                this.campo27Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo28 {
            get {
                return this.campo28Field;
            }
            set {
                this.campo28Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo29 {
            get {
                return this.campo29Field;
            }
            set {
                this.campo29Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo30 {
            get {
                return this.campo30Field;
            }
            set {
                this.campo30Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo31 {
            get {
                return this.campo31Field;
            }
            set {
                this.campo31Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo32 {
            get {
                return this.campo32Field;
            }
            set {
                this.campo32Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo33 {
            get {
                return this.campo33Field;
            }
            set {
                this.campo33Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo34 {
            get {
                return this.campo34Field;
            }
            set {
                this.campo34Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo35 {
            get {
                return this.campo35Field;
            }
            set {
                this.campo35Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo36 {
            get {
                return this.campo36Field;
            }
            set {
                this.campo36Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo37 {
            get {
                return this.campo37Field;
            }
            set {
                this.campo37Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo38 {
            get {
                return this.campo38Field;
            }
            set {
                this.campo38Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo39 {
            get {
                return this.campo39Field;
            }
            set {
                this.campo39Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo40 {
            get {
                return this.campo40Field;
            }
            set {
                this.campo40Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo41 {
            get {
                return this.campo41Field;
            }
            set {
                this.campo41Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo42 {
            get {
                return this.campo42Field;
            }
            set {
                this.campo42Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo43 {
            get {
                return this.campo43Field;
            }
            set {
                this.campo43Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo44 {
            get {
                return this.campo44Field;
            }
            set {
                this.campo44Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo45 {
            get {
                return this.campo45Field;
            }
            set {
                this.campo45Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo46 {
            get {
                return this.campo46Field;
            }
            set {
                this.campo46Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo47 {
            get {
                return this.campo47Field;
            }
            set {
                this.campo47Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo48 {
            get {
                return this.campo48Field;
            }
            set {
                this.campo48Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo49 {
            get {
                return this.campo49Field;
            }
            set {
                this.campo49Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo50 {
            get {
                return this.campo50Field;
            }
            set {
                this.campo50Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void Insert_HeaderCompletedEventHandler(object sender, Insert_HeaderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Insert_HeaderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Insert_HeaderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void Proc_DdjjCompletedEventHandler(object sender, Proc_DdjjCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Proc_DdjjCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Proc_DdjjCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void Proc_Ddjj_IdCompletedEventHandler(object sender, Proc_Ddjj_IdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Proc_Ddjj_IdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Proc_Ddjj_IdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public int DJ_ID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void Proc_LibroCompletedEventHandler(object sender, Proc_LibroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Proc_LibroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Proc_LibroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstTiposSocietariosFiltradosCompletedEventHandler(object sender, LstTiposSocietariosFiltradosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstTiposSocietariosFiltradosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstTiposSocietariosFiltradosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstWorkFlowCompletedEventHandler(object sender, LstWorkFlowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstWorkFlowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstWorkFlowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetLegalesCompletedEventHandler(object sender, GetLegalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLegalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLegalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstTiposSocietariosCompletedEventHandler(object sender, LstTiposSocietariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstTiposSocietariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstTiposSocietariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstTiposDocumentosCompletedEventHandler(object sender, LstTiposDocumentosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstTiposDocumentosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstTiposDocumentosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstCategoriaPEPCompletedEventHandler(object sender, LstCategoriaPEPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstCategoriaPEPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstCategoriaPEPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstSubCategoriasPEPCompletedEventHandler(object sender, LstSubCategoriasPEPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstSubCategoriasPEPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstSubCategoriasPEPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstVinculoPEPCompletedEventHandler(object sender, LstVinculoPEPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstVinculoPEPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstVinculoPEPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstTiposClaveFiscalCompletedEventHandler(object sender, LstTiposClaveFiscalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstTiposClaveFiscalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstTiposClaveFiscalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstTiposCargoCompletedEventHandler(object sender, LstTiposCargoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstTiposCargoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstTiposCargoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstTiposCargoFiltradosCompletedEventHandler(object sender, LstTiposCargoFiltradosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstTiposCargoFiltradosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstTiposCargoFiltradosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstTiposDJCompletedEventHandler(object sender, LstTiposDJCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstTiposDJCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstTiposDJCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstTiposMonedasCompletedEventHandler(object sender, LstTiposMonedasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstTiposMonedasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstTiposMonedasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstTiposValuacionFiltradosCompletedEventHandler(object sender, LstTiposValuacionFiltradosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstTiposValuacionFiltradosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstTiposValuacionFiltradosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstTiposValuacionCompletedEventHandler(object sender, LstTiposValuacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstTiposValuacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstTiposValuacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstTiposInstrumentoCompletedEventHandler(object sender, LstTiposInstrumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstTiposInstrumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstTiposInstrumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstTiposCuentaBancoCompletedEventHandler(object sender, LstTiposCuentaBancoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstTiposCuentaBancoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstTiposCuentaBancoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstTiposDictamenCompletedEventHandler(object sender, LstTiposDictamenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstTiposDictamenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstTiposDictamenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstTiposAsambleaCompletedEventHandler(object sender, LstTiposAsambleaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstTiposAsambleaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstTiposAsambleaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstTiposDocRubricaCompletedEventHandler(object sender, LstTiposDocRubricaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstTiposDocRubricaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstTiposDocRubricaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetMembreteCompletedEventHandler(object sender, GetMembreteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMembreteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMembreteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void LstTiposEstadosCivilesCompletedEventHandler(object sender, LstTiposEstadosCivilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LstTiposEstadosCivilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LstTiposEstadosCivilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591